version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    ports:
      - "43456:80"
    restart: always
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-php
    restart: always
    volumes:
      - ./www:/htdocs/www
